# Site settings
title: Martin Hinz
subtitle: Archaeology // Quantification // Information Technology

email: mail@martinhinz.info

description: > # this means to ignore newlines until "baseurl:"
  My personal webpage about my work, archaeology and quantitative research
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.martinhinz.info" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  MartinHinz

# Build settings
markdown: kramdown

scholar:
  style: apa
  locale: en
 
  sort_by: year
  order: descending
 
  source: ./_bibliography
  bibliography: personal.bib
  bibliography_template: "{{reference}}"
 
  replace_strings: true
  join_strings:    true
 
  details_dir:    bibliography
  details_layout: bib_details.html
  details_link:   Details
 
  query: "@*"

