# Site settings
title: Martin Hinz
subtitle: Archaeology // Quantification // Information Technology

email: mail@martinhinz.info

description: > # this means to ignore newlines until "baseurl:"
  My personal webpage about my work, archaeology and quantitative research
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.martinhinz.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: 0000-0002-9904-6548.bib
#  bibliography_template: "{{reference}}"
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bib_details.html
#  details_link:   Details

  query: "@*"

author:
  orcid: 0000-0002-9904-6548
  twitter_username: martinusrihhi
  github_username:  MartinHinz
  academia_username:  MartinHinz

exclude: ['_site', '_bibliography']
